# Generated by Django 2.2.7 on 2022-02-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endtoend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='empref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='endtoend.Emp'),
        ),
    ]
