# Generated by Django 2.2.7 on 2021-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='emp_name')),
                ('age', models.IntegerField(verbose_name='emp_age')),
                ('salary', models.FloatField(verbose_name='emp_salary')),
                ('role', models.CharField(max_length=20, verbose_name='emp_role')),
            ],
            options={
                'db_table': 'emp_info',
            },
        ),
    ]
