# Generated by Django 2.2.7 on 2022-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
