# Generated by Django 3.2.7 on 2021-09-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='emp_email'),
        ),
    ]
